### PR TITLE
Allow for the domain of the scores to be auto-inferred

### PR DESCRIPTION
**Pull request by oltionchampari**
Requires https://github.com/datavisyn/tdp_core/pull/604
### Summary
* Added `[null, null]` as domain for the scores to trigger the auto-inferring from lineup
In my tests, columns have the correct domain (tested with `[NaN, NaN]`)
Regarding the rankings we still use the `DbViewBuilder.deriveDefault()` to derive the min max, but I do not think we need to change that since it already works. Correct me if I am wrong.
With these changes the score limits are as in ordino-daily.
* I think we can ignore the dist file changes, it seems to not have been properly compiled before.

### Without setting domain to [ null, null ]

scores_before

### After setting domain to [ null, null ]

scores_after

### CODE REVIEW

**Review by thinkh — COMMENTED** [review]
The code-changes and result on the screenshot looks fine to me. 

> Regarding the rankings we still use the DbViewBuilder.deriveDefault() to derive the min max, but I do not think we need to change that since it already works. Correct me if I am wrong.

Good point! We might still need this call because `derive_columns` in `create_common` is also retrieving the categories. I'm not sure if we need this, because for example the chromosomes are defined in a config.ts. Could you please test the categorical (and numerical) columns without the `.derive_columns()`?

https://github.com/Caleydo/tdp_publicdb/blob/a7e10ab1217b2f19ebd1837cf09c0e41f4510e83/tdp_publicdb/query_common.py#L4-L15

**Review by thinkh — CHANGES_REQUESTED** [review]
Please test as described in the previous comment. Thanks.

**Comment by oltionchampari** [comment]
Tested removing the `derive_columns()` and that requires some refactoring in the frontend because some functions like `toChromosme()` (we can pass that as categoryOrder now) depend on the categories from the backend. We can remove/simplify some code in the `config.ts` and let LineUp derive the categories too

**Comment by oltionchampari** [comment]
We decided to keep the  `.derive_columns()` in common.py since there is some refactoring in lineup needed to derive the categories. 
The lineup builder that should be used i.e.,` buildCatecoricalColumn` spits out an empty  categories array which then you have to  set to null in order for lineup to trigger the deriving.
In addition, the interfaces have to be refactored to sync the builder interfaces with the ranking interfaces. We will address this in another issue

Note: min values that were originally  set to 0 have been set to 0 again since it was wanted behavior

**Review by thinkh — DISMISSED** [review]
Thanks. Looks good to me.

**Review by thinkh — APPROVED** [review]

**Pull request merged**
