### PR TITLE
Update to postgres 10

### LINKED ISSUE #49: Update to postgres 10
The new h38 release requires Postgres 10. We need to update the docker-compose.partial.yml.

### PR DESCRIPTION
**Pull request by thinkh**
Closes #49

### CODE REVIEW

**Comment by thinkh** [comment]
**Important**

Existing docker container with Postgres 9.6 (e.g., in a local workspace setup) do not work with this new Postgres 10 container!

```
db_publicdb_1  | 2019-07-18 20:23:48.850 UTC [1] FATAL:  database files are incompatible with server
db_publicdb_1  | 2019-07-18 20:23:48.850 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 10.9.
ordino_db_publicdb_1 exited with code 1
```

@anita-steiner can you please have a look if we can migrate the data automatically, or if developers have to restore the local database dump again?

**Comment by anita-steiner** [comment]
you have to move the data manually; see: https://peter.grman.at/upgrade-postgres-9-container-to-10/

**Comment by thinkh** [comment]
I would merge this PR as this version should only affect the local postgres container and our customers use already Postgres 10.

@anita-steiner What do you think? If you agree, please go ahead and merge the PR.

**Comment by thinkh** [comment]
Closed in favor of #82.

**Pull request closed without merging**
