### PR TITLE
Add feature to paste ids in the dataset search bar

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes the `copy-paste` feature described in Caleydo/tdp_bi_bioinfodb#1235
The `file drop` will be implemented in an another issue

### Summary 
* Changed the style of the select box to match that of the select2
* Implemented the pasting of the ids into the search bar

### Screenshot
grafik

### CODE REVIEW

**Comment by thinkh** [comment]
@oltionchampari Please resolve the merge conflicts by merging the `bootstrap-v4` into your branch. Thanks.

**Comment by oltionchampari** [comment]
@thinkh I implemented the feedback we discussed
Added the invalid selection styles 
Added the specific token separators for each dataset as they were in https://github.com/Caleydo/tdp_publicdb/blob/f99fc70af41e9a15ee3acf2f3eac4390d3b76e29/src/menu/SampleSubSection.ts#L26

grafik

**Review by thinkh — CHANGES_REQUESTED** [review]
When I copy and paste genes from Excel (or a text editor) into the field I get the valid genes twice (once as invalid and once as valid):

ordino-paste-genes-doublicates

@oltionchampari Can you please have a look again?

You can try it by pasting the following text into the search field: 

```txt
EGFR
ABL1
A1BG
MISSING
```

**Review by thinkh — APPROVED** [review]
Now it works as expected and it looks good to me! Thanks for your implementation.

**Pull request merged**
